### PR TITLE
maruos: TWRP bringup

### PR DESCRIPTION
**Pull request by NoelMacwan**

### CODE REVIEW

**Comment by pdsouza** [comment]
Can you drop the "rename master to ..." commit? We still use master branch for mostly everything. Then I can test just the TWRP merge, thanks!

**Comment by NoelMacwan** [comment]
thats why i committed the change, its better we have branches like that, to follow up what Android version the branch is.

**Comment by pdsouza** [comment]
It's pretty easy to just check the manifest itself to see which exact Android tag master is based off of currently.

The thing that I don't like about AOSP is that I have to guess about which branch/tag I need to be using all the time. I prefer keeping "master" as main development branch so there is no guesswork...all new stuff goes on master, always. If there's a branch called "android-5.0", I have no idea if that's a parallel development branch that's still in use, or not.  

I'm also not a fan of cherry-picking my commits everywhere when we move to the next version of Android, I prefer to just merge AOSP upstream into master. When Maru moved from L to M, it was as simple as creating a temporary feature branch for merging M, doing a "Merge android-6.0 into master" and updating the manifest. With this strategy, there is no point in having versioned branches because they all share the same history.

There are also lots of Maru repositories like blueprints, installer, etc that are not related to android at all--it makes no sense to have a branch "android-x.y" for them. All branch names should tell me something about Maru, not about android. 

I added this info to the Developer Guide so there is no confusion: https://github.com/maruos/maruos/wiki/Developer-Guide#branching.

We can discuss this further later on if you still disagree, but please drop the commit for now so I can at least test the TWRP stuff, thanks.

**Comment by NoelMacwan** [comment]
Commit reverted, force pushed.

**Comment by pdsouza** [comment]
Thanks!

**Comment by pdsouza** [comment]
Looks like there is a dependency on busybox:

```
Import includes file: out/target/product/hammerhead/obj/RECOVERY_EXECUTABLES/twrpbu_intermediates/import_includes
make: *** No rule to make target `out/target/product/hammerhead/system/xbin/busybox', needed by `out/target/product/hammerhead/obj/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin'.  Stop.
make: *** Waiting for unfinished jobs....
Export includes file: bootable/recovery/adbbu/Android.mk -- out/target/product/hammerhead/obj/RECOVERY_EXECUTABLES/twrpbu_intermediates/export_includes

#### make failed to build some targets (01:29 (mm:ss)) ####
```

We actually ship prebuilt busybox in `bin` but not `xbin`.

**Comment by pdsouza** [comment]
I patched the busybox error but still run into other build errors...

Anyways, I am not convinced that shipping TWRP by default is a great idea for most devices. I don't think there is a pressing need for it, and I think the cons outweight the pros here. 

The only positive that I see is that users have one less step to restore gapps (if that's something they want to do, some people use alternatives like F-Droid which does not require TWRP to install). Regarding the need of a PC: 1) either new users have TWRP already installed, so they can just install the update zip and keep their TWRP, or 2) they need a PC anyway to flash Maru OS via the easy installers, so they can just flash TWRP afterwards. People seem to be able to do this easily on with the forum instructions.

On the negatives, I see we need to use their version of `external/sepolicy` which has security-critical stuff, and I'd rather use the AOSP repo for that. I see that they have patched it in a couple of places, especially bypassing sepolicy for recovery and changing some of the neverallow rules... I took careful care in developing Maru OS to not touch any `external/sepolicy` rules, which is why we use AOSP's version. Changing neverallow rules are a bad idea because Maru OS will not pass any official Android testing, which would limit commercial use-cases. In general, I like keeping 3rd party dependencies to a minimum, using safe defaults, and letting users choose what they want to use themselves.

BUT, like you said, I agree this could be useful on Sony devices since they do not have a separate recovery partition, otherwise it would be very hard to restore gapps. 

So let's just ship TWRP on Sony devices with your custom maruos-sony manifest for now as a compromise.

**Comment by NoelMacwan** [comment]
Okay.

**Pull request closed without merging**
