### PR TITLE
manifest: android-7.1.2_r3 --> android-7.1.2_r28

### PR DESCRIPTION
**Pull request by NoelMacwan**

### CODE REVIEW

**Comment by pdsouza** [comment]
Sorry for the delay on merging these in Noel! Can you please add your "Signed-off-by" on this commit like you did on your previous manifest commits? You can skip it for pure merge commits but I'd like to have it whenever you introduce a code change, even if its trivial like this for bookkeeping 😃

**Comment by NoelMacwan** [comment]
Ops, I forgot, Forced pushed. :+1:

**Comment by pdsouza** [comment]
Thanks for fixing that! 

I checked the tags and it looks like r33 is on the `nougat-mr2.3-release` branch? I think it may be better to merge in r28 which is the latest on `nougat-mr2-release` since we will not be crossing branches which could lead to some duplicate commits and stuff down the road. I'm sure both r28 and r33 are almost identical but sticking to tags on this branch will cut down on merging headaches in the future I think. This is also the latest official release for the Nexus 5X/6P which are the primary devices in development for Maru on N. See https://groups.google.com/d/msg/android-building/lSlWVBBEjO8/osbUX7DACAAJ for the tags and associated devices. Let me know what you think about this...

**Comment by NoelMacwan** [comment]
In that case, it would be better to go with r29. If you're up for it, will send PR for that. ;)

**Comment by pdsouza** [comment]
That would be great! android-7.1.2_r28 (N2G48C) is the tag. Appreciate you taking the time to do this Noel!

**Comment by NoelMacwan** [comment]
Alright, so android-7.1.2_r28 or android-7.1.2_r29 ?

**Comment by pdsouza** [comment]
android-7.1.2_r28 is the latest on nougat-mr2-release, so r28 is the one. See https://android.googlesource.com/platform/build/+log/nougat-mr2-release.

**Comment by pdsouza** [comment]
DId a test build and things look good, thanks Noel!!

**Pull request merged**
