### PR TITLE
Android 6.0.1 Release 72 (M4B30X)

### PR DESCRIPTION
**Pull request by NoelMacwan**

### CODE REVIEW

**Comment by pdsouza** [comment]
Hi Noel, thanks for sending this!

Please read the [contributing guidelines[(https://github.com/maruos/maruos/blob/master/CONTRIBUTING.md#sign-your-work) about signing your work and add the "Signed-off-by: ..." tag to your commit message `git commit -s`. You can update a previous commit with `git commit --amend --signoff`. This is required for all commits before they can be merged. Your other PRs will need to be updated too. 

I'll pull them and test them as soon as this is corrected -- thanks!

**Comment by NoelMacwan** [comment]
Hey,
I just amend the commit(s) and forced push it.

**Comment by pdsouza** [comment]
Thank you for signing your work!

I pulled this and tried to sync but I ran into one error:

    Fetching project platform/packages/apps/Exchange
    fatal: Couldn't find remote ref refs/tags/android-6.0.1_r72

It looks like the Exchange app was removed in r72 and doesn't have the tag: https://android.googlesource.com/platform/manifest/+/a78a11076e7081be8b94c2f2a004791a7735fbbf%5E%21/#F0

Please update your commit to remove the Exchange app as in the commit above. I would remove it myself but I like the commits to be atomic if possible (easy rollback if needed) and don't want to add a commit on top of this.

Other than that everything looks good!

**Comment by NoelMacwan** [comment]
Ops, i just forgot about it, updated it.

**Comment by pdsouza** [comment]
All merged! Thanks again @NoelMacwan!

**Pull request merged**
